server:
  port: 8081

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /doc/swagger-ui.html

spring:
  application:
    name: ms-catalogo-service

  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true

  datasource:
    url: jdbc:mysql://localhost:3306/ms-catalogo
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka
  instance:
    hostname: localhost

